/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Run;

import Class.Bacsi;
import Class.BacsiDAO;
import Class.Benhnhan;
import Class.BenhnhanDAO;
import javax.swing.JOptionPane;


/**
 *
 * @author NGHIA_PC
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tktxt = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        mktxt = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 380));
        setPreferredSize(new java.awt.Dimension(550, 383));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Đăng nhập");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));
        getContentPane().add(tktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 310, 40));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCheckBox1.setText("Remember your account");
        jCheckBox1.setActionCommand("");
        jCheckBox1.setContentAreaFilled(false);
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
        getContentPane().add(mktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 310, 40));

        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 40));

        jButton3.setText("Login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 80, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tài khoản");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mật khẩu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 80, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("If you don't have account. Please");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, 30));

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("<HTML><U>Register!</U></HTML>");
        jButton4.setToolTipText(""); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 80, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngtree-tooth-display-board-background-material-image_141294.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(550, 380));
        jLabel1.setPreferredSize(new java.awt.Dimension(550, 380));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TTCaNhan.ID = tktxt.getText(); 
        TTCaNhanBN.sdt = tktxt.getText();
        TKCN.ID = tktxt.getText();
        KhoThuoc.ID = tktxt.getText();
        DSBenh.ID = tktxt.getText();
        Laphoso.ID = tktxt.getText();
        DatLichKham.ID = tktxt.getText();
        TimkiemThuoc.ID = tktxt.getText();
        DatLichKham.sdt = tktxt.getText();
        TTCuaHang.ID = tktxt.getText();
        CheckUpdate.ID = tktxt.getText();
        DonThuocChiTiet.idbs = tktxt.getText();
        
        
        String username = tktxt.getText();
        String password = mktxt.getText();
        
        if (username.equals("") && !password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập tài khoản!");
            return;
        } else if (password.equals("") && !username.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập mật khẩu!");
            return;
        } else if (username.equals("") && password.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Nhập đầy đủ tài khoản và mật khẩu!");
            return;
        }
        
        int count = 0;
        if (tktxt.getText().startsWith("BS"))
        {
            for (Bacsi tk : new BacsiDAO().getListBacsi()) {
            if (username.equals(tk.getID()) && password.equals(tk.getMK())) {
                count++;

                if (jCheckBox1.isSelected()) {
                    JOptionPane.showMessageDialog(rootPane, "Tài khoản được ghi nhớ!");
                }

               
                MenuBS menu = new MenuBS();
                this.setVisible(false);
                menu.setVisible(true);
                

            } 
        }
        
        }
        else 
        {
            for (Benhnhan tk : new BenhnhanDAO().getListBenhnhan()) {
                if (username.equals(tk.getSDT()) && password.equals(tk.getMK())) {
                    count++;

                    if (jCheckBox1.isSelected()) {
                        JOptionPane.showMessageDialog(rootPane, "Tài khoản được ghi nhớ!");
                    }


                    MenuBN menunv = new MenuBN();
                    this.setVisible(false);
                    menunv.setVisible(true);

                } 
        }
   
        }
        if (count == 0) {

            JOptionPane.showMessageDialog(rootPane, "Tài khoản không hợp lệ");
            }
                
        
    }//GEN-LAST:event_jButton3ActionPerformed
            
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tktxt.setText("");
        mktxt.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int lick=JOptionPane.showConfirmDialog(null,"Bạn Có Muốn Thoát Khỏi Chương Trình Hay Không?","Thông Báo",2);
        if(lick==JOptionPane.OK_OPTION){    
                System.exit(0);
            }
        else{
            if(lick==JOptionPane.CANCEL_OPTION){    
                this.setVisible(true);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Register r = new Register();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getRootPane().setDefaultButton(jButton3);
    }//GEN-LAST:event_formWindowOpened
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField mktxt;
    private javax.swing.JTextField tktxt;
    // End of variables declaration//GEN-END:variables
}
