/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Run;

import Class.Benhnhan;
import Class.BenhnhanDAO;;
import Class.Bacsi;
import Class.BacsiDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author NGHIA_PC
 */
public class Register2 extends javax.swing.JFrame {

    static String Ten,Gioitinh,Diachi,SDT,Email;
    static Date Ngaysinh;
    static String tk;
    static String cv;
    private ArrayList<Bacsi> list_info;
    private ArrayList<Benhnhan> list_pat;
    private int flag = 0;
    /**
     * Creates new form Register
     */
    public Register2() {
        initComponents();
        setLocationRelativeTo(null);
        list_info = new BacsiDAO().getListBacsi();
        list_pat = new BenhnhanDAO().getListBenhnhan();
        if (cv.equals("Bệnh nhân"))
        {
            tktxt.setText(tk);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tktxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(465, 460));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tài khoản");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mật khẩu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Xác nhận ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 40));

        tktxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tktxtKeyPressed(evt);
            }
        });
        getContentPane().add(tktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 270, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setToolTipText("<html><u>Back</u></html>"); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setDoubleBuffered(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 30));

        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, 70, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Đăng ký tài khoản");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jButton3.setText("Next");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 70, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Register");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 90, 40));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 270, 40));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 270, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngtree-cartoon-dentist-dental-health-background-image_190781.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(448, 670));
        jLabel1.setPreferredSize(new java.awt.Dimension(465, 455));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Register r = new Register();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        tktxtKeyPressed();
        
       
        if (jPasswordField1.getText().equals(jPasswordField2.getText()))
        {
            Bacsi tt = new Bacsi();
            Benhnhan bn = new Benhnhan();
            
            // Them bac si
            tt.setTen(Ten);
            tt.setGioitinh(Gioitinh);
            tt.setNgaysinh(Ngaysinh);
            tt.setDiachi(Diachi);
            tt.setSDT(SDT);
            tt.setEmail(Email);
            tt.setMK(jPasswordField1.getText());
            tt.setID(tktxt.getText());
         
            // Them benh nhan
            bn.setTen(Ten);
            bn.setGioitinh(Gioitinh);
            bn.setNgaysinh(Ngaysinh);
            bn.setSDT(SDT);
            bn.setDiaChi(Diachi);
            bn.setEmail(Email);
            bn.setMK(jPasswordField1.getText());
            
            if(tktxt.getText().startsWith("BS"))
            {
                new BacsiDAO().AddBacsi(tt);
                list_info.add(tt);
            }
            else
            {
                new BenhnhanDAO().AddBenhnhan(bn);
                list_pat.add(bn);
            }
            JOptionPane.showMessageDialog(rootPane, "Tài khoản được tạo thành công. Quay trở lại trang đăng nhập!");

            Login lg = new Login();
            this.setVisible(false);
            lg.setVisible(true);}
//            if(new TaikhoanDAO().AddAcc(tk))
//            {
//                if (Chucvu.equals("Bác sĩ"))
//                {
//                    new BacsiDAO().AddBacsi(tt);
//                    list_info.add(tt);
//                }
//                else
//                {
//                    new BenhnhanDAO().AddBenhnhan(bn);
//                    list_pat.add(bn);
//                }
//                
//                list_acc.add(tk);
//                
//                JOptionPane.showMessageDialog(rootPane, "Tài khoản được tạo thành công. Quay trở lại trang đăng nhập!");
//                
//                Login lg = new Login();
//                this.setVisible(false);
//                lg.setVisible(true);
//            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Xác nhận mật khẩu không thành công!");
            }
//            
//        }
        
    }//GEN-LAST:event_jButton4ActionPerformed


    private void tktxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tktxtKeyPressed
        // TODO add your handling code here:
        for (Bacsi t:new BacsiDAO().getListBacsi())
        {
            if (tktxt.getText().equals(t.getID()))
            {
                flag += 1;
            }

        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            if (flag == 0) {
                jLabel3.setText("Tên tài khoản hợp lệ");

            }
            if (flag != 0) {
                jLabel3.setText("Tên tài khoản đã được sử dụng!");
                flag = 0;
            }
        }
       
               

                
            
    }//GEN-LAST:event_tktxtKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getRootPane().setDefaultButton(jButton4);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField tktxt;
    // End of variables declaration//GEN-END:variables

    private Register Register() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
